### ISSUE TITLE
Source for ScratchDesktop.dat?

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [gbear605/ScratchToJAR#1]
I was wondering where ScratchDesktop.dat came from and where I could get the source. (Sorry, this isn't a real issue but I don't see any other way to ask)

Thanks!

~ MegaApuTurkUltra

**Comment by gbear605** [comment]
Sorry, I didn't make this, I just uploaded it to GitHub. I'm afraid I
don't know.

**Comment by MegaApuTurkUltra** [comment]
So then where did you get the code/files?
