### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JayBFC** [gbear605/ScratchToJAR#2]
It doesn't work. All it does is destroy my scratch project. When I compile it, it doesn't create the Jar file and it doesn't let me open the .sb file on my desktop. Please help.

**Comment by jfipjagw0j** [comment]
Change the .sb2 to .Jar

**Comment by gbear605** [comment]
This project is unfortunately only for Scratch version 1, and .sb2 files
are produced by Scratch 2, so this won’t work for you.
