### ISSUE TITLE
How do I get my project file from this compiled version

### ISSUE THREAD

**Issue by spacebytee** [gbear605/ScratchToJAR#4]
This bugged out and override my project file and I NEED IT BACK REALLY BAD, I PUT HOURS INTO IT, AND IT GOT OVER WRITTEN, HELP ME PLEASE

**Comment by spacebytee** [comment]
If there is no way can you PLEASE PLEASE PLEASE PELASE make a reverse engineer version to help me get my project now, I feel so sad HELP ME PELASE HELP ME

**Comment by gbear605** [comment]
Hi,
Unfortunately there's no way to get the project file back. I'm really sorry that this happened.
